# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmm_core_defs"
edition.workspace = true
rust-version.workspace = true

[package.metadata.verus]
verify = true

[dependencies]
vstd.workspace = true
virt.workspace = true

inspect.workspace = true
mesh.workspace = true

[lints]
workspace = true
